name: Update Pinned Repos
on:
  schedule:
    - cron: "0 0 * * *" # Runs daily
  workflow_dispatch: # Allows manual triggering
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update Pinned Repos
        uses: athul/pinned-repos-workflow@v1
        with:
          github_username: "psykiiib"
